org.gradle.jvmargs=-Xmx4G
android.useAndroidX=true
android.enableJetifier=true

# Work around Kotlin incremental compilation issues on Windows when the project and
# dependencies live on different drive letters (e.g., project on D: and Pub cache on C:).
kotlin.incremental=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
